version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file: .env.prod
    restart: unless-stopped
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file: .env.prod
    restart: unless-stopped
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
